version: '3'
services:
  magentadb:
    image: postgres:15.4
    restart: always
    ports:
      - '54321:5432'
    environment:
      POSTGRES_USER: magenta_user
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: magenta